import { Job } from "./types";

export const jobs: Job[] = [
  {
    id: "JOB-1021",
    product: "Brake Housing Unit",
    customer: "Tata Motors",
    quantity: 450,
    dueDate: "2026-09-15",
    status: "Delayed",
    machine: "CNC-02",
    notes: "Spindle vibration alarm triggered during rough milling pass. Tool head recalibrated; awaiting batch inspection clearance.",
  },
  {
    id: "JOB-1022",
    product: "Gear Assembly Kit",
    customer: "Bajaj Auto Parts",
    quantity: 1200,
    dueDate: "2026-09-18",
    status: "In Progress",
    machine: "MILL-01",
    notes: "First stage hobbing cycle completed (600/1200 units). Coolant temperature nominal at 21.5°C.",
  },
  {
    id: "JOB-1023",
    product: "Conveyor Belt Plate",
    customer: "Larsen & Toubro",
    quantity: 320,
    dueDate: "2026-09-18",
    status: "In Progress",
    machine: "PRESS-01",
    notes: "High-tonnage stamping active. Hydraulic pressure steady at 180 bar. On track for afternoon dispatch.",
  },
  {
    id: "JOB-1024",
    product: "Valve Body Cover",
    customer: "Bosch India",
    quantity: 800,
    dueDate: "2026-09-14",
    status: "Delayed",
    machine: "CNC-04",
    notes: "Raw material billet hardness variance out of spec. Heat treatment batch audit underway with metallurgist.",
  },
  {
    id: "JOB-1025",
    product: "Shaft Coupling Ring",
    customer: "Kirloskar Brothers",
    quantity: 150,
    dueDate: "2026-09-12",
    status: "Completed",
    machine: "LATHE-01",
    notes: "Finished turning and deburring. Quality report stamped and signed. Transferred to outbound staging zone.",
  },
  {
    id: "JOB-1026",
    product: "Piston Rod Assembly",
    customer: "Mahindra Supply Co",
    quantity: 600,
    dueDate: "2026-09-19",
    status: "In Progress",
    machine: "CNC-01",
    notes: "Cylindrical grinding pass #2 underway. Surface roughness verification within 0.4 Ra tolerance.",
  },
  {
    id: "JOB-1027",
    product: "Filter Housing Cap",
    customer: "Cummins India",
    quantity: 350,
    dueDate: "2026-09-20",
    status: "Pending",
    machine: "PRESS-02",
    notes: "Die set installed and aligned. Waiting on aluminum alloy sheet coil stock from raw stores.",
  },
  {
    id: "JOB-1028",
    product: "Bearing Retainer Disc",
    customer: "BHEL Components",
    quantity: 900,
    dueDate: "2026-09-18",
    status: "In Progress",
    machine: "LATHE-02",
    notes: "Facing and grooving operations in progress. Cycle time running at 48 seconds per unit.",
  },
  {
    id: "JOB-1029",
    product: "Cam Follower Bracket",
    customer: "Eaton Fluid Power",
    quantity: 240,
    dueDate: "2026-09-16",
    status: "Delayed",
    machine: "CNC-03",
    notes: "Carbide insert chipped on second axis pass. Tooling replaced; waiting for operator shift handover to restart.",
  },
  {
    id: "JOB-1030",
    product: "Hydraulic Manifold Block",
    customer: "Thermax Limited",
    quantity: 180,
    dueDate: "2026-09-21",
    status: "Pending",
    machine: "CNC-05",
    notes: "5-axis G-code verified on simulation sandbox. Production scheduled immediately after CNC-05 planned maintenance.",
  },
  {
    id: "JOB-1031",
    product: "Turbine Exhaust Flange",
    customer: "BHEL Components",
    quantity: 75,
    dueDate: "2026-09-10",
    status: "Completed",
    machine: "MILL-01",
    notes: "All bolt circle diameters verified on CMM machine. Ultrasonic flaw test negative. Batch approved.",
  },
  {
    id: "JOB-1032",
    product: "Drive Axle Pinion",
    customer: "Tata Motors",
    quantity: 500,
    dueDate: "2026-09-22",
    status: "In Progress",
    machine: "CNC-02",
    notes: "Tooth chamfering cycle active. Current yield at 98.6% conformance.",
  },
  {
    id: "JOB-1033",
    product: "Steering Knuckle Arm",
    customer: "Mahindra Supply Co",
    quantity: 320,
    dueDate: "2026-09-23",
    status: "Pending",
    machine: "PRESS-01",
    notes: "Billet induction heating coils pre-warming. Tooling inspection complete.",
  },
  {
    id: "JOB-1034",
    product: "Sensor Mounting Boss",
    customer: "Bosch India",
    quantity: 1400,
    dueDate: "2026-09-18",
    status: "Completed",
    machine: "LATHE-01",
    notes: "High-speed Swiss turning run finished ahead of schedule. Packaged in VCI anti-corrosion bags.",
  },
  {
    id: "JOB-1035",
    product: "Fuel Injector Nozzle Cap",
    customer: "Cummins India",
    quantity: 650,
    dueDate: "2026-09-17",
    status: "Delayed",
    machine: "CNC-01",
    notes: "Micro-hole EDM drilling electrode wear observed. Calibration required before resuming batch.",
  },
  {
    id: "JOB-1036",
    product: "Impeller Hub Spacer",
    customer: "Kirloskar Brothers",
    quantity: 280,
    dueDate: "2026-09-24",
    status: "Pending",
    machine: "LATHE-02",
    notes: "Stainless steel 316 bar stock allocated. Job scheduled for Friday night shift.",
  },
  {
    id: "JOB-1037",
    product: "Flywheel Ring Gear",
    customer: "Bajaj Auto Parts",
    quantity: 850,
    dueDate: "2026-09-08",
    status: "Completed",
    machine: "PRESS-02",
    notes: "Induction hardening cycle passed. Case depth measured at 1.8mm target.",
  },
  {
    id: "JOB-1038",
    product: "Heat Exchanger Core Plate",
    customer: "Thermax Limited",
    quantity: 400,
    dueDate: "2026-09-25",
    status: "Pending",
    machine: "CNC-04",
    notes: "Awaiting laser cutting schedule confirmation from Line B supervisor.",
  },
  {
    id: "JOB-1039",
    product: "Splined Input Shaft",
    customer: "Larsen & Toubro",
    quantity: 210,
    dueDate: "2026-09-06",
    status: "Completed",
    machine: "CNC-03",
    notes: "Spline broaching and nitriding complete. Ready for customer pickup.",
  },
  {
    id: "JOB-1040",
    product: "Pneumatic Cylinder Barrel",
    customer: "Eaton Fluid Power",
    quantity: 300,
    dueDate: "2026-09-19",
    status: "In Progress",
    machine: "LATHE-01",
    notes: "Internal bore honing in progress. Bore diameter tolerance verified at +0.012mm.",
  },
];
